#!/usr/bin/env bash

#PBS -l nodes=1:ppn=12
#PBS -l mem=64gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1
#PBS -N hla-mapper
#PBS -j oe
#PBS -o log/$PBS_JOBNAME

PBS_ARRAYID=1
PBS_NUM_PPN=12

FQLIST=/home/vitor/nci_hla/analysis/variant_calling/fastq_list.txt
SAMPLE=$( awk -v ARRID="$PBS_ARRAYID" 'FNR==ARRID { print $1 }' $FQLIST )
BAM=/scratch/vitor/results/star/one_pass/${SAMPLE}_Aligned.sortedByCoord.out.bam
OUT=/scratch/vitor/results/hlamapper/$SAMPLE

mkdir -p $OUT

/raid/genevol/users/vitor/hla-mapper_new/build/hla-mapper rna \
    bam=$BAM \
    sample=$SAMPLE \
    threads=$PBS_NUM_PPN \
    db=/raid/genevol/users/vitor/hla-mapper_new/db/hla-mapper_db_004.1_HLA \
    output=$OUT \
    bwa=/raid/genevol/users/vitor/HLAMAPPER/bwa/bwa-0.7.17/bwa \
    samtools=/raid/genevol/users/vitor/HLAMAPPER/samtools-1.11/samtools \
    star=/raid/genevol/users/vitor/HLAMAPPER/STAR-2.7.3a/bin/Linux_x86_64_static/STAR
