#!/usr/bin/env bash

#PBS -l nodes=1:ppn=4
#PBS -l mem=32gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1,3
#PBS -N GATKforASE
#PBS -j oe
#PBS -o /scratch/vitor/$PBS_JOBNAME

FQLIST=${PBS_O_WORKDIR}/fastq_list.txt
SAMPLE=$( awk -v ARRID="$PBS_ARRAYID" 'FNR==ARRID { print $1 }' $FQLIST)
ID=$( echo $SAMPLE | cut -d'_' -f1 )
BAMPREFIX=/scratch/vitor/results/star/pass_wasp/$SAMPLE
BAM=${BAMPREFIX}_Aligned.sortedByCoord.out.bam

# Extract uniquely mapped reads
samtools view -b -h -q 255 -@ $PBS_NUM_PPN $BAM > ${BAMPREFIX}.uniq.bam

# Mark duplicates
java -jar /usr/bin/picard.jar AddOrReplaceReadGroups \
    I=${BAMPREFIX}.uniq.bam \
    O=${BAMPREFIX}.uniq.rg.bam \
    RGID=readGroupID${PBS_ARRAYID} \
    RGLB=libraryID \
    RGPL=ILLUMINA \
    RGPU=HiSeq \
    RGSM=$ID \
    TMP_DIR=/scratch/vitor/temp

gatk MarkDuplicatesSpark \
    -I ${BAMPREFIX}.uniq.rg.bam \
    -O ${BAMPREFIX}.uniq.mkdups.bam \
    --tmp-dir /scratch/vitor/temp \
    --spark-master local[$PBS_NUM_PPN]

# Extract reads that passed WASP filter
samtools view -h -@ $PBS_NUM_PPN ${BAMPREFIX}.uniq.mkdups.bam |\
    awk '$0 ~ /^@/ || $0 ~ /vW:i:1/' |\
    samtools view -Sb -@ $PBS_NUM_PPN - > ${BAMPREFIX}.aseinput.bam

rm ${BAMPREFIX}.uniq.*
