#!/usr/bin/env bash

#PBS -l nodes=1:ppn=8
#PBS -l mem=48gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -t 1-125
#PBS -N STAR2nd
#PBS -j oe
#PBS -o /raid/genevol/users/vitor/log/$PBS_JOBNAME

cd $PBS_O_WORKDIR

FQLIST=./fastq_list.txt

# List of junction files
SAMPLELIST=( $( awk '{ print $ 1}' $FQLIST) )
STAR1ST=./results/star/pass_1st 
SJDB=( "${SAMPLELIST[@]/#/$STAR1ST/}" )
SJDB=( "${SJDB[@]/%/_SJ.out.tab}" )
SJDBLIST=$( echo ${SJDB[*]} )

# Sample FASTQs
SAMPLEID=$( awk -v ARRID="$PBS_ARRAYID" 'FNR==ARRID { print $1 }' $FQLIST )
FQ1=$( awk -v ARRID="$PBS_ARRAYID" 'FNR==ARRID { print $2 }' $FQLIST )
FQ2=$( awk -v ARRID="$PBS_ARRAYID" 'FNR==ARRID { print $3 }' $FQLIST )

# Index and output
INDEX=./INDEX
OUTDIR=./results/star/pass_2nd
OUT=${OUTDIR}/${SAMPLEID}

mkdir -p $OUTDIR

# Command
STAR --runMode alignReads \
    --runThreadN $PBS_NUM_PPN \
    --genomeDir $INDEX \
    --readFilesIn $FQ1 $FQ2 \
    --readFilesCommand zcat  \
    --outFilterMismatchNoverReadLmax 0.04 \
    --sjdbFileChrStartEnd $SJDBLIST \
    --outSAMtype BAM SortedByCoordinate \
    --outFileNamePrefix ${OUT}_
