#!/usr/bin/env bash

#PBS -l nodes=1:ppn=12
#PBS -l mem=48gb
#PBS -l walltime=24:00:00
#PBS -q short
#PBS -N STARindex
#PBS -j oe
#PBS -o /home/vitor/log/$PBS_JOBNAME

cd $PBS_O_WORKDIR

GENOME=/raid/genevol/gencode/GRCh38.primary_assembly.genome.fa
GTF=/raid/genevol/gencode/gencode.v39.primary_assembly.annotation.gtf
OUT=INDEX

mkdir -p $OUT

STAR --runThreadN $PBS_NUM_PPN \
    --runMode genomeGenerate \
    --genomeDir $OUT \
    --genomeFastaFiles $GENOME \
    --sjdbGTFfile $GTF
